
export const metadata = {
  title: "routeDemo - Create Next App",
  description: "routeDemo - Generated by create next app",
};

export default function UseRouteLayout({ children }) {
  return (
    <div>
      <div>useRoute-layout-header</div>
      {children}
      <div>useRoute-layout-footer</div>
    </div>
  );
}
