import theme from '@/config/theme';
import StyledComponentsRegistry from '@/libs/antdRegistry';
import "@/styles/globals.css";
import { App, ConfigProvider } from 'antd';
import zhCN from 'antd/locale/zh_CN';
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <ConfigProvider locale={zhCN} theme={theme}>
            <App>
              {children}
            </App>
          </ConfigProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
