
export const metadata = {
  title: "routeDemo - Create Next App",
  description: "routeDemo - Generated by create next app",
};

export default function RouteDemoLayout({ children }) {
  return (
    <div>
      <div>route-demo-layout-Header</div>
      {children}
      <div>route-demo-layout-footer</div>
    </div>
  );
}
